export const dateKey = (offset = 0) => {
  const d = new Date();
  d.setDate(d.getDate() + offset);
  return `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, "0")}-${String(d.getDate()).padStart(2, "0")}`;
};
export const formatDate = (value, options = {}) =>
  new Date(`${value}T12:00:00`).toLocaleDateString("en-IN", {
    day: "numeric",
    month: "short",
    ...options,
  });
export const money = (value) =>
  new Intl.NumberFormat("en-IN", {
    style: "currency",
    currency: "INR",
    maximumFractionDigits: 0,
  }).format(value);
export const doctors = [
  {
    id: "meera",
    name: "Dr. Meera Iyer",
    specialty: "General medicine",
    qualification: "MBBS, MD · Internal Medicine",
    experience: 14,
    languages: "English, Hindi, Kannada",
    fee: 700,
    image: "/images/doctor-meera.jpg",
    rating: "4.9",
    reviews: 128,
    locations: ["indiranagar", "whitefield"],
    about:
      "A patient-first approach to everyday health, preventive care and the management of long-term conditions.",
    next: "10:30 AM",
  },
  {
    id: "arjun",
    name: "Dr. Arjun Rao",
    specialty: "Cardiology",
    qualification: "MBBS, MD, DM · Cardiology",
    experience: 18,
    languages: "English, Hindi, Kannada",
    fee: 1000,
    image: "/images/doctor-arjun.jpg",
    rating: "4.9",
    reviews: 206,
    locations: ["indiranagar", "jayanagar"],
    about:
      "Focused on preventive cardiology and supporting patients through every stage of their heart health journey.",
    next: "11:00 AM",
  },
  {
    id: "rohan",
    name: "Dr. Rohan Menon",
    specialty: "Orthopaedics",
    qualification: "MBBS, MS · Orthopaedics",
    experience: 12,
    languages: "English, Hindi, Malayalam",
    fee: 800,
    image: "/images/doctor-rohan.jpg",
    rating: "4.8",
    reviews: 94,
    locations: ["indiranagar", "whitefield", "jayanagar"],
    about:
      "Care for joint, bone and movement concerns with a focus on recovery and everyday mobility.",
    next: "02:00 PM",
  },
  {
    id: "ananya",
    name: "Dr. Ananya Shah",
    specialty: "Dermatology",
    qualification: "MBBS, MD · Dermatology",
    experience: 10,
    languages: "English, Hindi",
    fee: 850,
    image: "",
    rating: "4.8",
    reviews: 112,
    locations: ["indiranagar", "whitefield"],
    about:
      "Personalised consultations for skin and hair concerns, with clear explanations and practical follow-up care.",
    next: "03:30 PM",
  },
];
export const specialties = [
  ["All specialties", "category"],
  ["General medicine", "health"],
  ["Cardiology", "heart"],
  ["Orthopaedics", "activity"],
  ["Dermatology", "sun"],
];
export const slots = [
  "09:00 AM",
  "09:30 AM",
  "10:00 AM",
  "10:30 AM",
  "11:00 AM",
  "11:30 AM",
  "02:00 PM",
  "02:30 PM",
  "03:00 PM",
  "03:30 PM",
  "04:00 PM",
  "04:30 PM",
];
export const packages = [
  {
    id: "essential",
    name: "A little check-in. A healthier you.",
    shortName: "Essential health check",
    description: "A thoughtful starting point for your annual health check.",
    tests: "32 parameters",
    price: 1499,
    oldPrice: 2200,
    tag: "PREVENTIVE CARE",
    icon: "health",
    includes: [
      "Complete blood count",
      "Blood glucose",
      "Lipid profile",
      "Liver function",
      "Doctor review",
    ],
    collection: true,
  },
  {
    id: "heart",
    name: "Give your heart a little attention.",
    shortName: "Heart health package",
    description: "A closer look at your cardiovascular health.",
    tests: "18 parameters + ECG",
    price: 2499,
    oldPrice: 3500,
    tag: "HEART HEALTH",
    icon: "heart",
    includes: ["Lipid profile", "HbA1c", "ECG", "Cardiology consultation"],
    collection: false,
  },
  {
    id: "senior",
    name: "More care for the ones who cared.",
    shortName: "Senior wellness package",
    description: "Comprehensive care for the people who matter most.",
    tests: "56 parameters",
    price: 3499,
    oldPrice: 4800,
    tag: "FAMILY WELLNESS",
    icon: "people",
    includes: [
      "Complete blood count",
      "Kidney and liver function",
      "Thyroid profile",
      "Vitamin B12",
      "Physician review",
    ],
    collection: true,
  },
];
export function initialState() {
  return {
    version: 1,
    activeMember: "self",
    location: "indiranagar",
    members: [
      {
        id: "self",
        name: "Aarav Sharma",
        relation: "Self",
        dob: "1994-05-12",
        gender: "Male",
        blood: "B+",
        phone: "9000000001",
        email: "aarav@example.com",
        mrn: "TP-10482",
        allergies: "No known allergies",
        access: "Full access",
      },
      {
        id: "father",
        name: "Rajesh Sharma",
        relation: "Father",
        dob: "1962-11-08",
        gender: "Male",
        blood: "B+",
        phone: "9000000002",
        mrn: "TP-10483",
        allergies: "Penicillin",
        access: "Full access",
      },
      {
        id: "mother",
        name: "Sunita Sharma",
        relation: "Mother",
        dob: "1966-03-21",
        gender: "Female",
        blood: "O+",
        phone: "9000000003",
        mrn: "TP-10484",
        allergies: "No known allergies",
        access: "Full access",
      },
    ],
    appointments: [
      {
        id: "TP-24091",
        memberId: "self",
        doctorId: "meera",
        date: dateKey(),
        time: "10:30 AM",
        status: "Confirmed",
        location: "indiranagar",
        type: "In-person",
        reason: "Routine health consultation",
        source: "Hospital",
        queue: {
          token: "A-012",
          ahead: 3,
          minutes: 18,
          room: "Consultation room 04",
          checkedIn: false,
        },
      },
      {
        id: "TP-24072",
        memberId: "father",
        doctorId: "arjun",
        date: dateKey(2),
        time: "11:00 AM",
        status: "Confirmed",
        location: "indiranagar",
        type: "In-person",
        reason: "Follow-up consultation",
        source: "Family",
      },
      {
        id: "TP-23916",
        memberId: "self",
        doctorId: "meera",
        date: dateKey(-14),
        time: "09:30 AM",
        status: "Completed",
        location: "indiranagar",
        type: "In-person",
        reason: "Annual health review",
        source: "Patient",
      },
      {
        id: "TP-23888",
        memberId: "mother",
        doctorId: "rohan",
        date: dateKey(-21),
        time: "02:00 PM",
        status: "Completed",
        location: "jayanagar",
        type: "In-person",
        reason: "Follow-up",
        source: "Hospital",
      },
    ],
    records: [
      {
        id: "r1",
        memberId: "self",
        title: "Complete blood count",
        category: "Lab reports",
        date: dateKey(-2),
        author: "Hospital laboratory",
        doctorId: "meera",
        format: "PDF",
        new: true,
        values: [
          ["Haemoglobin", "14.2", "g/dL"],
          ["White blood cells", "7,200", "/µL"],
          ["Platelets", "2,45,000", "/µL"],
        ],
        note: "Illustrative sample results. Not a real diagnostic report.",
      },
      {
        id: "r2",
        memberId: "self",
        title: "Consultation prescription",
        category: "Prescriptions",
        date: dateKey(-14),
        author: "Dr. Meera Iyer",
        doctorId: "meera",
        format: "PDF",
        note: "Sample consultation record. Medication details will come from the signed prescription in the hospital EMR.",
      },
      {
        id: "r3",
        memberId: "self",
        title: "Chest X-ray report",
        category: "Scans & imaging",
        date: dateKey(-30),
        author: "Radiology department",
        format: "PDF",
        note: "Sample imaging record. The signed report and images will be provided by the hospital.",
      },
      {
        id: "r4",
        memberId: "father",
        title: "Cardiology consultation",
        category: "Prescriptions",
        date: dateKey(-7),
        author: "Dr. Arjun Rao",
        format: "PDF",
        note: "Sample follow-up record. View the signed clinical document after EMR integration.",
      },
      {
        id: "r5",
        memberId: "mother",
        title: "Discharge summary",
        category: "Discharge summaries",
        date: dateKey(-21),
        author: "Inpatient care team",
        format: "PDF",
        note: "Sample discharge record from a completed hospital stay.",
      },
    ],
    bills: [
      {
        id: "INV-1048",
        memberId: "self",
        title: "General medicine consultation",
        date: dateKey(),
        amount: 700,
        status: "Unpaid",
        items: [["Consultation fee", 700]],
      },
      {
        id: "INV-1021",
        memberId: "self",
        title: "Laboratory investigations",
        date: dateKey(-2),
        amount: 1200,
        status: "Paid",
        method: "UPI",
        transaction: "DEMO-728410",
        items: [
          ["Complete blood count", 400],
          ["Lipid profile", 800],
        ],
      },
      {
        id: "INV-0946",
        memberId: "father",
        title: "Cardiology consultation",
        date: dateKey(-7),
        amount: 1000,
        status: "Paid",
        method: "Card",
        transaction: "DEMO-728211",
        items: [["Consultation fee", 1000]],
      },
    ],
    notifications: [
      {
        id: "n1",
        title: "Your lab report is ready",
        body: "Your complete blood count report is now available in Health records.",
        date: "2 hours ago",
        route: "/records",
        icon: "document-text",
        read: false,
        memberId: "self",
      },
      {
        id: "n2",
        title: "We’re expecting you today",
        body: "Your appointment with Dr. Meera Iyer is at 10:30 AM. Please arrive 15 minutes early.",
        date: "3 hours ago",
        route: "/appointments",
        icon: "calendar-2",
        read: false,
        memberId: "self",
      },
      {
        id: "n3",
        title: "A little care goes a long way",
        body: "Explore preventive health packages for you and your family.",
        date: "Yesterday",
        route: "/packages",
        icon: "heart",
        read: true,
      },
    ],
    vaccines: [
      {
        id: "v1",
        memberId: "self",
        name: "Influenza",
        status: "Discuss with doctor",
        date: dateKey(14),
        note: "Ask your clinician about eligibility and timing.",
      },
      {
        id: "v2",
        memberId: "self",
        name: "Hepatitis B",
        status: "Recorded",
        date: dateKey(-180),
        note: "Sample historical vaccination record.",
      },
      {
        id: "v3",
        memberId: "father",
        name: "Pneumococcal",
        status: "Discuss with doctor",
        date: dateKey(21),
        note: "Ask your clinician about eligibility and timing.",
      },
    ],
    requests: [],
    contacts: [
      {
        id: "c1",
        name: "Rajesh Sharma",
        relation: "Father",
        phone: "9000000002",
      },
    ],
    preferences: { reminders: true, reports: true, promotions: false },
    feedback: [],
    healthLinks: {},
  };
}
