import { withAdminOverrides } from "./hospitalConfig.js";
import { soonSlot } from "./videoVisit.js";
export const dateKey = (offset = 0) => {
  const d = new Date();
  d.setDate(d.getDate() + offset);
  return `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, "0")}-${String(d.getDate()).padStart(2, "0")}`;
};
export const formatDate = (value, options = {}) =>
  new Date(`${value}T12:00:00`).toLocaleDateString("en-IN", {
    day: "numeric",
    month: "short",
    ...options,
  });
export const money = (value) =>
  new Intl.NumberFormat("en-IN", {
    style: "currency",
    currency: "INR",
    maximumFractionDigits: 0,
  }).format(value);
const baseDoctors = [
  {
    id: "meera",
    name: "Dr. Meera Iyer",
    specialty: "General medicine",
    qualification: "MBBS, MD · Internal Medicine",
    experience: 14,
    languages: "English, Hindi, Kannada",
    image: "/images/doctor-meera.jpg",
    locations: ["indiranagar", "whitefield"],
    about:
      "A patient-first approach to everyday health, preventive care and the management of long-term conditions.",
    next: "10:30 AM",
  },
  {
    id: "arjun",
    name: "Dr. Arjun Rao",
    specialty: "Cardiology",
    qualification: "MBBS, MD, DM · Cardiology",
    experience: 18,
    languages: "English, Hindi, Kannada",
    image: "/images/doctor-arjun.jpg",
    locations: ["indiranagar", "jayanagar"],
    about:
      "Focused on preventive cardiology and supporting patients through every stage of their heart health journey.",
    next: "11:00 AM",
  },
  {
    id: "rohan",
    name: "Dr. Rohan Menon",
    specialty: "Orthopaedics",
    qualification: "MBBS, MS · Orthopaedics",
    experience: 12,
    languages: "English, Hindi, Malayalam",
    image: "/images/doctor-rohan.jpg",
    locations: ["indiranagar", "whitefield", "jayanagar"],
    about:
      "Care for joint, bone and movement concerns with a focus on recovery and everyday mobility.",
    next: "02:00 PM",
  },
  {
    id: "ananya",
    name: "Dr. Ananya Shah",
    specialty: "Dermatology",
    qualification: "MBBS, MD · Dermatology",
    experience: 10,
    languages: "English, Hindi",
    image: "",
    locations: ["indiranagar", "whitefield"],
    about:
      "Personalised consultations for skin and hair concerns, with clear explanations and practical follow-up care.",
    next: "03:30 PM",
  },
];
// Doctors and availability come from Tatva Practice, which has no fee
// setting: consultation fees are set in the hospital console only, and a
// doctor without one is still bookable (the fee is paid at the clinic).
export const allDoctors = baseDoctors;
export const doctors = withAdminOverrides(baseDoctors);
// Fee for a visit type, or null when the hospital hasn't set one.
export const feeFor = (doctor, type) => {
  const fee =
    type === "Video consultation" ? (doctor?.videoFee ?? doctor?.fee) : doctor?.fee;
  return Number.isFinite(fee) ? fee : null;
};
export const specialties = [
  ["All specialties", "category"],
  ["General medicine", "health"],
  ["Cardiology", "heart"],
  ["Orthopaedics", "activity"],
  ["Dermatology", "sun"],
];
export const slots = [
  "09:00 AM",
  "09:30 AM",
  "10:00 AM",
  "10:30 AM",
  "11:00 AM",
  "11:30 AM",
  "02:00 PM",
  "02:30 PM",
  "03:00 PM",
  "03:30 PM",
  "04:00 PM",
  "04:30 PM",
  "05:30 PM",
  "06:00 PM",
  "06:30 PM",
];
export const packages = [
  {
    id: "essential",
    category: "Preventive care",
    name: "A little check-in. A healthier you.",
    shortName: "Essential health check",
    description: "A thoughtful starting point for your annual health check.",
    tests: "32 parameters",
    price: 1499,
    oldPrice: 2200,
    tag: "PREVENTIVE CARE",
    icon: "health",
    includes: [
      "Complete blood count",
      "Blood glucose",
      "Lipid profile",
      "Liver function",
      "Doctor review",
    ],
    collection: true,
  },
  {
    id: "heart",
    category: "Preventive care",
    name: "Give your heart a little attention.",
    shortName: "Heart health package",
    description: "A closer look at your cardiovascular health.",
    tests: "18 parameters + ECG",
    price: 2499,
    oldPrice: 3500,
    tag: "HEART HEALTH",
    icon: "heart",
    includes: ["Lipid profile", "HbA1c", "ECG", "Cardiology consultation"],
    collection: false,
  },
  {
    id: "senior",
    category: "Preventive care",
    name: "More care for the ones who cared.",
    shortName: "Senior wellness package",
    description: "Comprehensive care for the people who matter most.",
    tests: "56 parameters",
    price: 3499,
    oldPrice: 4800,
    tag: "FAMILY WELLNESS",
    icon: "people",
    includes: [
      "Complete blood count",
      "Kidney and liver function",
      "Thyroid profile",
      "Vitamin B12",
      "Physician review",
    ],
    collection: true,
  },
  {
    id: "laboratory",
    category: "Lab & pathology",
    name: "Know more about your health.",
    shortName: "Laboratory health check",
    description:
      "Routine blood and urine tests, reported by our pathology lab.",
    tests: "Blood & urine tests",
    price: 999,
    oldPrice: 1499,
    tag: "LAB & PATHOLOGY",
    icon: "clipboard-tick",
    includes: [
      "Complete blood count",
      "Blood glucose",
      "Urine routine",
      "Laboratory report",
    ],
    collection: true,
  },
  {
    id: "radiology",
    category: "Radiology",
    name: "A clearer picture of your health.",
    shortName: "Radiology imaging package",
    description:
      "Imaging with a radiologist's report. The care team confirms the right scan for your referral.",
    tests: "Imaging & reporting",
    price: 1799,
    oldPrice: 2200,
    tag: "RADIOLOGY",
    icon: "gallery",
    includes: ["Referral review", "X-ray imaging", "Radiologist report"],
    collection: false,
  },
];
const hoursAgo = (h) => new Date(Date.now() - h * 3600000).toISOString();
export function initialState() {
  return {
    version: 1,
    seedVersion: 3,
    activeMember: "self",
    location: "indiranagar",
    members: [
      {
        id: "self",
        name: "Aarav Sharma",
        relation: "Self",
        dob: "1994-05-12",
        gender: "Male",
        blood: "B+",
        phone: "9000000001",
        email: "aarav@example.com",
        mrn: "TP-10482",
        allergies: "No known allergies",
        access: "Full access",
      },
      {
        id: "father",
        name: "Rajesh Sharma",
        relation: "Father",
        dob: "1962-11-08",
        gender: "Male",
        blood: "B+",
        phone: "9000000002",
        mrn: "TP-10483",
        allergies: "Penicillin",
        access: "Full access",
      },
      {
        id: "mother",
        name: "Sunita Sharma",
        relation: "Mother",
        dob: "1966-03-21",
        gender: "Female",
        blood: "O+",
        phone: "9000000003",
        mrn: "TP-10484",
        allergies: "No known allergies",
        access: "Full access",
      },
    ],
    appointments: [
      {
        id: "TP-24091",
        memberId: "self",
        doctorId: "meera",
        date: dateKey(),
        time: "10:30 AM",
        status: "Confirmed",
        location: "indiranagar",
        type: "In-person",
        reason: "Routine health consultation",
        source: "Hospital",
      },
      {
        id: "TP-24095",
        memberId: "self",
        doctorId: "ananya",
        date: dateKey(),
        time: soonSlot(),
        status: "Confirmed",
        location: "indiranagar",
        type: "Video consultation",
        reason: "Follow-up on lab results",
        source: "Patient",
      },
      {
        id: "TP-24072",
        memberId: "father",
        doctorId: "arjun",
        date: dateKey(2),
        time: "11:00 AM",
        status: "Confirmed",
        location: "indiranagar",
        type: "In-person",
        reason: "Follow-up consultation",
        source: "Family",
      },
      {
        id: "TP-23916",
        memberId: "self",
        doctorId: "meera",
        date: dateKey(-14),
        time: "09:30 AM",
        status: "Completed",
        location: "indiranagar",
        type: "In-person",
        reason: "Annual health review",
        source: "Patient",
      },
      {
        id: "TP-23874",
        memberId: "self",
        doctorId: "ananya",
        date: dateKey(-35),
        time: "11:00 AM",
        status: "Completed",
        location: "indiranagar",
        type: "In-person",
        reason: "Skin rash on forearms",
        source: "Patient",
      },
      {
        id: "TP-23842",
        memberId: "self",
        doctorId: "arjun",
        date: dateKey(-62),
        time: "05:30 PM",
        status: "Completed",
        location: "whitefield",
        type: "Video",
        reason: "Palpitations after exercise",
        source: "Patient",
      },
      {
        id: "TP-23951",
        memberId: "father",
        doctorId: "arjun",
        date: dateKey(-7),
        time: "08:30 AM",
        status: "Completed",
        location: "indiranagar",
        type: "In-person",
        reason: "Blood pressure review",
        source: "Patient",
      },
      {
        id: "TP-23888",
        memberId: "mother",
        doctorId: "rohan",
        date: dateKey(-21),
        time: "02:00 PM",
        status: "Completed",
        location: "jayanagar",
        type: "In-person",
        reason: "Follow-up",
        source: "Hospital",
      },
    ],
    records: [
      {
        id: "r1",
        memberId: "self",
        title: "Complete blood count",
        category: "Lab reports",
        date: dateKey(-2),
        time: "10:42 AM",
        author: "Hospital laboratory",
        doctorId: "meera",
        format: "PDF",
        new: true,
        values: [
          ["Haemoglobin", "14.2", "g/dL"],
          ["White blood cells", "7,200", "/µL"],
          ["Platelets", "2,45,000", "/µL"],
        ],
      },
      {
        id: "r2",
        memberId: "self",
        title: "Consultation prescription",
        category: "Prescriptions",
        date: dateKey(-14),
        time: "11:15 AM",
        author: "Dr. Meera Iyer",
        doctorId: "meera",
        appointmentId: "TP-23916",
        format: "PDF",
        rx: {
          complaints: "Routine annual review. Occasional tiredness in the evenings.",
          vitals: "BP 124/80 mmHg · Pulse 76/min · Weight 68 kg · SpO2 98%",
          diagnosis: "Vitamin D insufficiency",
          medicines: [
            ["Cholecalciferol 60,000 IU", "1 sachet", "Once a week, after food", "8 weeks"],
            ["Multivitamin", "1 tablet", "Once a day, after breakfast", "30 days"],
          ],
          tests: "Vitamin D (25-OH) after 8 weeks",
          advice: "20 minutes of morning sunlight. Brisk walk 30 minutes a day.",
          followUp: "After 8 weeks with the Vitamin D report",
        },
      },
      {
        id: "r3",
        memberId: "self",
        title: "Chest X-ray report",
        category: "Scans & imaging",
        date: dateKey(-30),
        time: "04:20 PM",
        author: "Radiology department",
        format: "PDF",
      },
      {
        id: "r4",
        memberId: "father",
        title: "Cardiology consultation",
        category: "Prescriptions",
        date: dateKey(-7),
        time: "09:05 AM",
        author: "Dr. Arjun Rao",
        doctorId: "arjun",
        appointmentId: "TP-23951",
        format: "PDF",
        rx: {
          complaints: "Follow-up for blood pressure. No chest pain or breathlessness.",
          vitals: "BP 138/86 mmHg · Pulse 72/min · Weight 78 kg",
          diagnosis: "Essential hypertension, controlled",
          medicines: [
            ["Telmisartan 40 mg", "1 tablet", "Once a day, morning", "90 days"],
            ["Atorvastatin 10 mg", "1 tablet", "Once a day, night", "90 days"],
          ],
          tests: "Lipid profile and kidney function before the next visit",
          advice: "Salt under 5 g a day. Walk 30 minutes daily. Check BP twice a week.",
          followUp: "After 3 months",
        },
      },
      {
        id: "r10",
        memberId: "self",
        title: "Dermatology prescription",
        category: "Prescriptions",
        date: dateKey(-35),
        time: "11:25 AM",
        author: "Dr. Ananya Shah",
        doctorId: "ananya",
        appointmentId: "TP-23874",
        format: "PDF",
        rx: {
          complaints: "Itchy red rash on both forearms for 10 days, worse after gardening.",
          vitals: "BP 120/78 mmHg · Pulse 74/min",
          diagnosis: "Allergic contact dermatitis",
          medicines: [
            ["Mometasone 0.1% cream", "Thin layer", "Once a day, night", "10 days"],
            ["Levocetirizine 5 mg", "1 tablet", "Once a day, night", "7 days"],
          ],
          advice: "Wear gloves while gardening. Use a fragrance-free moisturiser twice a day.",
          followUp: "If the rash is not better in 2 weeks",
        },
      },
      {
        id: "r11",
        memberId: "self",
        title: "Cardiology teleconsultation",
        category: "Prescriptions",
        date: dateKey(-62),
        time: "05:55 PM",
        author: "Dr. Arjun Rao",
        doctorId: "arjun",
        appointmentId: "TP-23842",
        format: "PDF",
        rx: {
          complaints: "Occasional palpitations after running, no chest pain or fainting.",
          diagnosis: "Palpitations, likely benign; to evaluate",
          medicines: [],
          tests: "ECG, 2D echo and thyroid profile",
          advice: "Limit caffeine. Stay hydrated during exercise.",
          followUp: "In-clinic visit with the test reports",
        },
      },
      {
        id: "r9",
        memberId: "mother",
        title: "Follow-up prescription",
        category: "Prescriptions",
        date: dateKey(-21),
        time: "02:40 PM",
        author: "Dr. Rohan Menon",
        doctorId: "rohan",
        appointmentId: "TP-23888",
        format: "PDF",
        rx: {
          complaints: "Right knee pain on climbing stairs, 3 weeks.",
          vitals: "BP 132/84 mmHg · Pulse 80/min · Weight 64 kg",
          diagnosis: "Early osteoarthritis, right knee",
          medicines: [
            ["Aceclofenac 100 mg", "1 tablet", "Twice a day, after food", "5 days"],
            ["Diclofenac gel", "Apply locally", "Three times a day", "2 weeks"],
          ],
          tests: "X-ray right knee, standing AP and lateral",
          advice: "Quadriceps strengthening exercises. Avoid squatting and cross-legged sitting.",
          followUp: "After 2 weeks with the X-ray",
        },
      },
      {
        id: "r5",
        memberId: "mother",
        title: "Discharge summary",
        category: "Discharge summaries",
        date: dateKey(-21),
        time: "06:30 PM",
        author: "Inpatient care team",
        format: "PDF",
      },
    ],
    bills: [
      {
        id: "INV-1048",
        memberId: "self",
        title: "General medicine consultation",
        date: dateKey(),
        amount: 700,
        status: "Outstanding",
        items: [["Consultation fee", 700]],
      },
      {
        id: "INV-1021",
        memberId: "self",
        title: "Laboratory investigations",
        date: dateKey(-2),
        amount: 1200,
        status: "Paid",
        method: "UPI at counter",
        transaction: "RCPT-728410",
        items: [
          ["Complete blood count", 400],
          ["Lipid profile", 800],
        ],
      },
      {
        id: "INV-0981",
        memberId: "self",
        appointmentId: "TP-23916",
        title: "General medicine consultation",
        date: dateKey(-14),
        amount: 700,
        status: "Paid",
        method: "UPI at counter",
        transaction: "RCPT-726904",
        items: [["Consultation fee", 700]],
      },
      {
        id: "INV-0921",
        memberId: "self",
        appointmentId: "TP-23874",
        title: "Dermatology consultation",
        date: dateKey(-35),
        amount: 850,
        status: "Paid",
        method: "Card at counter",
        transaction: "RCPT-724118",
        items: [["Consultation fee", 850]],
      },
      {
        id: "INV-0874",
        memberId: "self",
        appointmentId: "TP-23842",
        title: "Cardiology video consultation",
        date: dateKey(-62),
        amount: 900,
        status: "Paid",
        method: "UPI",
        transaction: "RCPT-721650",
        items: [["Video consultation fee", 900]],
      },
      {
        id: "INV-0962",
        memberId: "mother",
        appointmentId: "TP-23888",
        title: "Orthopaedics consultation",
        date: dateKey(-21),
        amount: 800,
        status: "Paid",
        method: "Cash at counter",
        transaction: "RCPT-726511",
        items: [["Follow-up consultation fee", 800]],
      },
      {
        id: "INV-0946",
        memberId: "father",
        appointmentId: "TP-23951",
        title: "Cardiology consultation",
        date: dateKey(-7),
        amount: 1000,
        status: "Paid",
        method: "Card at counter",
        transaction: "RCPT-728211",
        items: [["Consultation fee", 1000]],
      },
    ],
    notifications: [
      {
        id: "n1",
        type: "report",
        title: "Your lab report is ready",
        body: "Complete blood count is now in Health records.",
        createdAt: hoursAgo(2),
        route: "/records",
        read: false,
        memberId: "self",
      },
      {
        id: "n2",
        type: "appointment",
        appointmentId: "TP-24091",
        title: "We’re expecting you today",
        body: "Please arrive 15 minutes early.",
        createdAt: hoursAgo(3),
        route: "/appointments?visit=TP-24091",
        read: false,
        memberId: "self",
      },
    ],
    requests: [],
    packageRequests: [],
    // "Request a callback" from the hospital contacts, when enabled.
    callbackRequests: [],
    contacts: [
      {
        id: "c1",
        name: "Rajesh Sharma",
        relation: "Father",
        phone: "9000000002",
      },
    ],
    preferences: { reminders: true, reports: true, promotions: false },
    feedback: [],
    // Rajesh has a sample ABHA linked so the linked state can be explored.
    healthLinks: {
      father: {
        abha: {
          identifier: "12-3456-7890-1235",
          address: "rajesh.sharma@abdm",
          consentAt: hoursAgo(72),
          lastSyncAt: hoursAgo(26),
          demo: true,
        },
      },
    },
  };
}
