import { Fragment, useEffect, useState } from "react";
import { useNavigate, useSearchParams } from "react-router-dom";
import { useApp } from "../state/AppContext";
import {
  money,
  formatDate,
  dateKey,
  packages,
  doctors,
} from "../../shared/data";
import { locations, shiftRows } from "../../shared/brand";
import { readAdminConfig } from "../../shared/hospitalConfig";
import HospitalContacts from "../components/HospitalContacts";
import { download } from "../services/files";
import {
  Button,
  Badge,
  Avatar,
  Icon,
  PageHeader,
  SectionTitle,
  MemberContext,
  Field,
  ChoiceGroup,
  Empty,
  Sheet,
  Notice,
  ErrorText,
  Status,
  Row,
  Tag,
  useAction,
} from "../components/ui";
import { Divider } from "@dhspl-tatvacare/tesseract-ui";
import s from "../App.module.css";
export function Billing() {
  const { state, activeMember, brand } = useApp();
  const [tab, setTab] = useState("All");
  const [params, setParams] = useSearchParams();
  const [bill, setBillState] = useState(() =>
    state.bills.find((b) => b.id === params.get("bill")) || null,
  );
  const setBill = (b) => {
    setBillState(b);
    if (!b && params.get("bill")) setParams({}, { replace: true });
  };
  const bills = state.bills.filter((b) => b.memberId === activeMember.id);
  const shown = bills.filter((b) => tab === "All" || b.status === tab);
  const outstanding = bills.filter((b) => b.status === "Outstanding");
  const due = outstanding.reduce((sum, b) => sum + b.amount, 0);
  function saveDocument(b) {
    const paid = b.status === "Paid";
    download(
      `${b.id}-${paid ? "receipt" : "invoice"}.txt`,
      `${brand.hospitalName}\n${paid ? "PAYMENT RECEIPT" : "INVOICE"} (SAMPLE)\n\nInvoice: ${b.id}\nDate: ${formatDate(b.date)}\nPatient: ${activeMember.name}\n${b.title}\n${b.items.map(([name, amount]) => `${name}: ${money(amount)}`).join("\n")}\nTotal: ${money(b.amount)}\nStatus: ${b.status}${paid ? `\nPaid at hospital: ${b.method}\nReceipt: ${b.transaction}` : "\nPayable at the hospital billing desk."}`,
    );
  }
  return (
    <div className={s.page}>
      <PageHeader title="Bills & receipts" />
      <MemberContext />
      <div className={s.balanceCard}>
        <span className={s.balanceLabel}>Total outstanding</span>
        <div className={s.balanceAmount}>
          <strong>{money(due)}</strong>
          {due ? <Status status="Outstanding" /> : <Status status="Paid" />}
        </div>
        <p className={s.bodyText}>
          {due
            ? `${outstanding.length} ${outstanding.length === 1 ? "bill" : "bills"} · Payable at the hospital billing desk.`
            : "You’re all caught up."}
        </p>
      </div>
      <ChoiceGroup
        label="Bill status"
        hideLabel
        options={["All", "Outstanding", "Paid"]}
        value={tab}
        onChange={setTab}
      />
      <div className={s.stack}>
        {shown.map((b) => (
          <button className={s.billCard} key={b.id} onClick={() => setBill(b)}>
            <span className={s.billBody}>
              <span className={s.inlineMeta}>
                <span className={s.metaText}>
                  {b.id} · {formatDate(b.date)}
                </span>
                <Status status={b.status} />
              </span>
              <span className={s.billRow}>
                <h3 className={s.cardTitle}>{b.title}</h3>
                <strong>{money(b.amount)}</strong>
              </span>
              {b.status === "Paid" && b.method && (
                <span className={s.billPaid}>
                  {b.paidOn
                    ? `Paid on ${formatDate(b.paidOn)}`
                    : "Paid at hospital"}{" "}
                  · {b.method}
                </span>
              )}
            </span>
            <Icon
              name="chevron-right"
              size={16}
              color="var(--tesseract-fg-tertiary)"
            />
          </button>
        ))}
      </div>
      {!shown.length && (
        <Empty
          icon="bill"
          title="No bills to show"
          description="Bills generated by your hospital will appear here."
        />
      )}
      <Sheet
        open={!!bill}
        onClose={() => setBill(null)}
        title={bill?.status === "Paid" ? "Payment receipt" : "Invoice"}
      >
        {bill && (
          <>
            <div className={s.invoiceHead}>
              <h3>{bill.title}</h3>
              <span className={s.invoiceMeta}>
                <span className={s.metaText}>
                  {bill.id} · {formatDate(bill.date)} · For {activeMember.name}
                </span>
                <Status status={bill.status} />
              </span>
            </div>
            <dl className={s.invoiceLines}>
              {bill.items.map(([name, amount]) => (
                <div className={s.invoiceLine} key={name}>
                  <dt>{name}</dt>
                  <dd>{money(amount)}</dd>
                </div>
              ))}
            </dl>
            <Divider />
            <div className={s.invoiceTotal}>
              <strong>Total</strong>
              <strong>{money(bill.amount)}</strong>
            </div>
            {bill.status === "Paid" ? (
              <dl className={s.invoiceLines}>
                <div className={s.invoiceLine}>
                  <dt>Paid at hospital</dt>
                  <dd>{bill.method}</dd>
                </div>
                <div className={s.invoiceLine}>
                  <dt>Receipt no.</dt>
                  <dd>{bill.transaction}</dd>
                </div>
              </dl>
            ) : (
              <Notice>
                Please pay at the hospital billing desk. The status updates here
                once the hospital records your payment.
              </Notice>
            )}
            <Button
              variant="outline"
              fullWidth
              onClick={() => saveDocument(bill)}
            >
              <Icon name="document-download" />
              {bill.status === "Paid" ? "Download receipt" : "Download invoice"}
            </Button>
          </>
        )}
      </Sheet>
    </div>
  );
}
export function Hospital() {
  const { state, brand } = useApp();
  const hospital = locations.find((l) => l.id === state.location);
  const extras = readAdminConfig().clinicExtras?.[hospital.id] || {};
  const shifts = shiftRows(hospital.shifts);
  return (
    <div className={s.page}>
      <PageHeader title="Your hospital" />
      <div className={s.hospitalHero}>
        <Icon name="hospital" size={52} bulk />
        <h1>{brand.hospitalName}</h1>
        <p>
          {hospital.name}, {hospital.city}
        </p>
        <Badge color="success">Your selected location</Badge>
      </div>
      {extras.photos?.length > 0 && (
        <div className={s.clinicPhotos}>
          {extras.photos.map((src, i) => (
            <img key={i} src={src} alt={`${hospital.name} clinic, photo ${i + 1}`} />
          ))}
        </div>
      )}
      <div className={s.detailCard}>
        <h3>Getting here</h3>
        <p>
          {hospital.address}
          {hospital.pincode ? ` – ${hospital.pincode}` : ""}
        </p>
        {extras.note && <Notice icon="info-circle">{extras.note}</Notice>}
        <Button
          href={
            hospital.mapsUrl ||
            `https://www.google.com/maps/dir/?api=1&destination=${hospital.lat},${hospital.lng}`
          }
          target="_blank"
          rel="noopener noreferrer"
          fullWidth
        >
          <Icon name="routing" />
          Get directions
        </Button>
      </div>
      <div className={s.detailCard}>
        <h3>OPD timings</h3>
        {shifts.length ? (
          <dl className={s.shiftList}>
            {shifts.map(([days, times]) => (
              <Fragment key={days}>
                <dt>{days}</dt>
                <dd>
                  {times.split(" · ").map((time) => (
                    <span key={time}>{time}</span>
                  ))}
                </dd>
              </Fragment>
            ))}
          </dl>
        ) : (
          <p>{hospital.hours}</p>
        )}
      </div>
      <SectionTitle>Hospital contacts</SectionTitle>
      <HospitalContacts
        showEmpty
        desks={["bookingPhone", "whatsappPhone", "billingPhone", "supportPhone", "ambulancePhone"]}
      />
      <Button href="tel:112" variant="outline" theme="error" fullWidth>
        <Icon name="call-calling" />
        Emergency assistance · 112
      </Button>
    </div>
  );
}
